# Generated by Django 4.2.1 on 2023-07-08 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0002_initial'),
        ('main', '0001_initial'),
        ('job_seekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='city',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='cv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cv_experience', to='job_seekers.cv'),
        ),
        migrations.AddField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cv_education', to='job_seekers.cv'),
        ),
        migrations.AddField(
            model_name='cv',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
        migrations.AddField(
            model_name='cv',
            name='feedback',
            field=models.ManyToManyField(to='employers.employer'),
        ),
        migrations.AddField(
            model_name='cv',
            name='jobseeker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job_seekers.jobseeker'),
        ),
    ]
