# Generated by Django 4.2.1 on 2023-05-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
