# Generated by Django 4.2 on 2023-05-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_jobseeker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
