# Generated by Django 4.2.1 on 2023-05-22 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_occupation_id'),
        ('job_seekers', '0008_remove_jobseeker_address_jobseeker_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='desired_salary',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.AddField(
            model_name='cv',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate Degree'), ('license', 'Professional Certification/License'), ('courses', 'Courses/Training'), ('hight', 'hight school')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='cv',
            name='jobseeker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job_seekers.jobseeker'),
        ),
        migrations.AddField(
            model_name='cv',
            name='key_skills',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='cv',
            name='occupation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.occupation'),
        ),
        migrations.AddField(
            model_name='cv',
            name='salary',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='cv',
            name='schedule',
            field=models.CharField(choices=[('full', 'full-time'), ('flex', 'flexible'), ('shift', 'shift'), ('part', 'part-time'), ('seasonal', 'seasonal'), ('hybrid', 'hybrid')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='cv',
            name='standing',
            field=models.CharField(choices=[('none', 'without'), ('1', '1 year'), ('13', '1-3 year'), ('3', '3 year'), ('5', '5 year')], default='none', max_length=4),
        ),
    ]
