# Generated by Django 4.2.1 on 2023-05-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0009_remove_jobseeker_desired_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='experience',
        ),
    ]
