# Generated by Django 4.2.1 on 2023-05-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0010_remove_jobseeker_bio_remove_jobseeker_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to='job_seekers_photos/'),
        ),
    ]
