# Generated by Django 4.2.1 on 2023-05-28 01:27

from django.db import migrations, models
import job_seekers.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0012_remove_jobseeker_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to=job_seekers.models.JobSeeker.image_upload_to),
        ),
    ]
