# Generated by Django 4.2.1 on 2023-05-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0013_alter_jobseeker_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='jobseeker',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='standing',
        ),
    ]
