# Generated by Django 4.2.1 on 2023-05-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0015_cv_city_cv_education_cv_experience_cv_jobseeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='jobseeker',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='standing',
        ),
    ]
