# Generated by Django 4.2.1 on 2023-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0019_rename_occupation_experience_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='work_place',
            field=models.CharField(choices=[('full', 'full-time'), ('flex', 'flexibility'), ('home', 'from home')], default=None, max_length=4),
        ),
    ]
