# Generated by Django 4.2.1 on 2023-05-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0021_alter_cv_work_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='bio',
            field=models.TextField(default=None),
        ),
    ]
