# Generated by Django 4.2.1 on 2023-05-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0022_cv_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='city',
        ),
        migrations.AlterField(
            model_name='cv',
            name='bio',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cv',
            name='occupation',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
