# Generated by Django 4.2.1 on 2023-05-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0024_alter_jobseeker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.CharField(choices=[('none', 'Without education'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate Degree'), ('license', 'Professional Certification/License'), ('courses', 'Courses/Training'), ('hight', 'hight school')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='key_skills',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='occupation',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='salary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='schedule',
            field=models.CharField(choices=[('none', "doesn't matter"), ('full', 'full-time'), ('flex', 'flexible'), ('shift', 'shift'), ('part', 'part-time'), ('seasonal', 'seasonal'), ('hybrid', 'hybrid')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work_place',
            field=models.CharField(choices=[('none', "doesn't matter"), ('full', 'full-time'), ('flex', 'flexibility'), ('home', 'from home')], default=None, max_length=4, null=True),
        ),
    ]
