# Generated by Django 4.2.1 on 2023-05-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0026_remove_education_study_period_education_cv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='resume',
            new_name='cv',
        ),
    ]
