# Generated by Django 4.2.1 on 2023-05-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0027_rename_resume_experience_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'default_related_name': 'cv_education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'default_related_name': 'cv_experience'},
        ),
    ]
