# Generated by Django 4.2.1 on 2023-06-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_occupation_id'),
        ('job_seekers', '0030_alter_cv_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='city',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
    ]
