# Generated by Django 4.2.1 on 2023-06-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_message'),
        ('job_seekers', '0031_cv_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
    ]
