# Generated by Django 4.2.1 on 2023-07-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0023_alter_employer_city'),
        ('job_seekers', '0033_jobseeker_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='feedback',
            field=models.ManyToManyField(to='employers.employer'),
        ),
    ]
