# Generated by Django 4.2.1 on 2023-05-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Some',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_O', models.CharField(max_length=2)),
            ],
        ),
    ]
