# Generated by Django 4.2.1 on 2023-05-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_some'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Some',
        ),
    ]
