# Generated by Django 4.2.1 on 2023-05-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cities'),
        ('employers', '0007_delete_some'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
    ]
