# Generated by Django 4.2.1 on 2023-05-22 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_occupation_id'),
        ('employers', '0010_remove_vacancy_job_title_vacancy_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
    ]
