# Generated by Django 4.2.1 on 2023-05-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_occupation_id'),
        ('employers', '0012_employer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
    ]
