# Generated by Django 4.2.1 on 2023-05-28 01:27

from django.db import migrations, models
import employers.models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0013_alter_employer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to=employers.models.Employer.image_upload_to),
        ),
    ]
