# Generated by Django 4.2.1 on 2023-06-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0014_alter_employer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('none', 'Without education'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate Degree'), ('license', 'Professional Certification/License'), ('courses', 'Courses/Training'), ('hight', 'hight school')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
