# Generated by Django 4.2.1 on 2023-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0015_alter_vacancy_education_alter_vacancy_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='work_place',
            field=models.CharField(choices=[('none', "doesn't matter"), ('full', 'full-time'), ('flex', 'flexibility'), ('home', 'from home')], default=None, max_length=4),
        ),
    ]
