# Generated by Django 4.2.1 on 2023-06-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0016_vacancy_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(choices=[('none', "doesn't matter"), ('full', 'full-time'), ('flex', 'flexible'), ('shift', 'shift'), ('part', 'part-time'), ('seasonal', 'seasonal'), ('hybrid', 'hybrid')], default=None, max_length=10),
        ),
    ]
