# Generated by Django 4.2.1 on 2023-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0017_alter_vacancy_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
