# Generated by Django 4.2.1 on 2023-06-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_cities_id'),
        ('employers', '0022_alter_vacancy_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
    ]
