# Generated by Django 4.2.1 on 2023-07-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0034_cv_feedback'),
        ('employers', '0023_alter_employer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='feedback',
            field=models.ManyToManyField(to='job_seekers.jobseeker'),
        ),
    ]
