# Generated by Django 4.2.1 on 2023-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
