# Generated by Django 4.2.1 on 2023-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acc_type',
            field=models.CharField(choices=[('JS', 'job_seeker'), ('ER', 'employer')], default=None, max_length=20),
        ),
    ]
