# Generated by Django 4.2.1 on 2023-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_acc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acc_type',
            field=models.CharField(choices=[('JS', 'job_seeker'), ('ER', 'employer')], default='ER', max_length=20),
        ),
    ]
