# Generated by Django 4.2.1 on 2023-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_acc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acc_type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
