# Generated by Django 4.2 on 2023-05-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acc_type',
            new_name='user_type',
        ),
    ]
