# Generated by Django 4.2.1 on 2023-05-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
    ]
