# Generated by Django 4.2.1 on 2023-05-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_cities_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='Citie',
        ),
    ]
