# Generated by Django 4.2.1 on 2023-05-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_cities_citie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citie',
            new_name='Cities',
        ),
    ]
