# Generated by Django 4.2.1 on 2023-05-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_citie_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
