# Generated by Django 4.2.1 on 2023-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
    ]
