# Generated by Django 4.2.1 on 2023-05-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
    ]
