# Generated by Django 4.2.1 on 2023-06-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
