# Generated by Django 4.2.1 on 2023-05-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_city_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Cityus',
        ),
    ]
