# Generated by Django 4.2.1 on 2023-05-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_geol_delete_cityus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geol',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='geol',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='geol',
            old_name='state',
            new_name='state_name',
        ),
        migrations.AlterModelTable(
            name='geol',
            table='city',
        ),
    ]
