# Generated by Django 4.2.1 on 2023-05-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_geol_options_rename_city_geol_city_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='geol',
            table=None,
        ),
    ]
