# Generated by Django 4.2.1 on 2023-05-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_geol_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geol',
        ),
    ]
