# Generated by Django 4.2.1 on 2023-05-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city_table',
        ),
    ]
