# Generated by Django 4.2.1 on 2023-05-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_city_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
    ]
