# Generated by Django 4.2.1 on 2023-05-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
