# Generated by Django 4.2.1 on 2023-05-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_citytable_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CityTable',
        ),
    ]
