# Generated by Django 4.2.1 on 2023-06-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0022_alter_vacancy_city'),
        ('job_seekers', '0033_jobseeker_date_of_birth'),
        ('chat', '0002_delete_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_user1', to='employers.employer')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_user2', to='job_seekers.jobseeker')),
            ],
        ),
    ]
